name: Snyk Container Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '38 19 * * 3'

permissions:
  contents: read

jobs:
  snyk-container-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          curl -sL https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Run Snyk Container Test and generate SARIF
        continue-on-error: true
        run: |
          snyk container test my-image:latest \
            --file=Dockerfile \
            --sarif > snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif
